# Generated by Django 5.2.10 on 2026-02-03 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBlockedSlot',
            fields=[
                ('blocked_id', models.AutoField(primary_key=True, serialize=False)),
                ('blocked_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(choices=[('unavailable', 'Unavailable'), ('off_duty', 'Off-duty')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='scheduling.doctor')),
            ],
            options={
                'db_table': 'doctor_blocked_slots',
                'ordering': ['blocked_date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='start_time_before_end_time')],
            },
        ),
    ]
