# Generated by Django 5.2.10 on 2026-02-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_doctorblockedslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('preferred_time_range', models.CharField(blank=True, choices=[('MORNING', '09:00–12:00'), ('MIDDAY', '12:00–14:00'), ('AFTERNOON', '14:00–17:00')], max_length=20, null=True)),
                ('preferred_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_gender', models.CharField(choices=[('any', 'Any'), ('M', 'Male'), ('F', 'Female')], default='any', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='scheduling.patient')),
            ],
            options={
                'db_table': 'patient_preferences',
            },
        ),
    ]
