# Generated by ChatGPT for Appointment model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_make_requestdate_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.doctor')),
            ],
            options={
                'db_table': 'appointments',
                'unique_together': {('doctor', 'slot_start', 'slot_end')},
            },
        ),
    ]
