# Generated by ChatGPT to add penalty field to Appointment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='penalty',
            field=models.IntegerField(blank=True, help_text='Solver penalty score for this assignment', null=True),
        ),
    ]
